# SkillHub Backend - Configuration SonarCloud

sonar.projectKey=Nirina2108_skillhub_CICD_backend
sonar.projectName=skillhub_CICD_backend
sonar.projectVersion=1.0
sonar.organization=nirina2108

sonar.sources=app
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.php.tests.reportPath=build/logs/junit.xml

sonar.exclusions=vendor/**,node_modules/**,database/**,storage/**,bootstrap/**,public/**,resources/**

sonar.coverage.exclusions=app/Http/Middleware/**,app/Providers/**,app/Mail/**,app/Console/**,app/Http/Controllers/MessageController.php,app/Models/Message.php,app/Models/FormationVue.php

sonar.cpd.exclusions=app/Http/Middleware/**,app/Providers/**
